import type { Metadata } from "next";

// import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MarketingLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
    >
      <body className="min-h-full flex flex-col">
        <header
          style={{
            backgroundColor: "grey",
            padding: "5px",
            height: "200px",
            width: "100%",
          }}
        >
          <p>Header</p>
        </header>
        <main>{children}</main>
        <footer
          style={{
            backgroundColor: "whitesmoke",
            padding: "5px",
            height: "200px",
            width: "100%",
          }}
        >
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
